### ISSUE TITLE
last name must between 3 and 30 characters

### ISSUE THREAD

**Issue by lilaxuan** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#10]
**Describe the bug**
When I tried to register a new account, and I entered my last name"Li", it shows the error that "last name must between 3 and 30 characters", would you resolve this issue since some of the people, their last name might be less than 3 lol. 
**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="398" alt="image" src="https://user-images.githubusercontent.com/106371956/177899666-ecbef541-9488-4644-a82f-996447cd1e6a.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by george-q-liu** [comment]
fixed
