### ISSUE TITLE
Friends button takes user to home

### ISSUE THREAD

**Issue by erkita** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#11]
**Describe the bug**
When a logged in user goes to another person's profile and click "friends", it takes the user to homepage, https://neu5500.netlify.app/.

**To Reproduce**
1. Log in to user profile
2. Go to other user's profile page
3. Click "Friends" tab of the viewing profile page
4. See homepage

**Expected behavior**
See friends of other user

**Desktop (please complete the following information):**
 - OS

**Comment by george-q-liu** [comment]
fixed
