### ISSUE TITLE
Not able to use phone number to create user

### ISSUE THREAD

**Issue by LincolnCardosodeFaria** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#2]
**Describe the bug**

**To Reproduce**
1. Go to '...' Create Account
2. Click on '....' mobile or email 
"Enter a valid email address"

**Expected behavior**

The field expects a mobile number or email 

**Screenshots**

![image](https://user-images.githubusercontent.com/18237521/177898348-74828346-aafd-477b-8a4e-6c8390561b27.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser  chrome,
 - Version 103.0.5060.114

**Additional context**

**Comment by george-q-liu** [comment]
can't support phone number registrations, removed that part
