### ISSUE TITLE
Date of Birth fields not clear

### ISSUE THREAD

**Issue by bonicim** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#3]
**Describe the bug**
When a user tries to register their account, the fields for date of birth are not clear. Is the first field for the month or day? Is the second field for the month or day?

**To Reproduce**
1. Go to Create account
2. Go to Date of birth text boxes

**Expected behavior**
I want to know clearly what is the month or day for date of birth fields. 

**Screenshots**
<img width="443" alt="Screen Shot 2022-07-07 at 18 33 09" src="https://user-images.githubusercontent.com/6901848/177898721-34b4f54f-abc2-4226-84ab-b041a19ce93d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by george-q-liu** [comment]
added DD/MM/YYYY
