### ISSUE TITLE
Notification and new story(?) notification

### ISSUE THREAD

**Issue by cathylee12** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#4]
**Describe the bug**
I don't have any new updates but it says I have 5 new notifications and 9 new stories to watch.

**To Reproduce**
1. Go to 'main page'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47257080/177898942-c8d171b8-4558-4977-af1f-2420fc0aea66.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by george-q-liu** [comment]
they are just placeholders for testing only. Implementing a notification system is not in the scope of project. Thanks for the feedback!
