### ISSUE TITLE
Upload picture redirect error

### ISSUE THREAD

**Issue by LincolnCardosodeFaria** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#5]
**Describe the bug**

**To Reproduce**
1. Go to '...' profile
2. Click on '....' upload picure
 no action from the site
**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/18237521/177899244-ecb43e1a-fb94-41c2-a38e-4c7cd796ab19.png)

Desktop (please complete the following information):

OS: Windows 11
Browser chrome,
Version 103.0.5060.114
Additional context

**Additional context**

**Comment by george-q-liu** [comment]
fixed
