### ISSUE TITLE
SUGGESTION: Add "Day, Month, and Year" text in DOB boxes in Account Creation

### ISSUE THREAD

**Issue by kevbvan** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#6]
**Describe the bug**
When creating an account the text boxes for your birthday are not clear.

**To Reproduce**
1. Click "Create an Account"

**Expected behavior**
Each box to say "Day", "Month", "Year" respectively to make clear what box is what

**Screenshots**

![image](https://user-images.githubusercontent.com/106618858/177899459-f3b5da12-f912-4b28-8765-2fc15fb5027e.png)

**Desktop (please complete the following information):**
 - Windows 10, Google Chrome

**Comment by george-q-liu** [comment]
added DDMMYYYY
