### ISSUE TITLE
Can't create an account with some date of birth

### ISSUE THREAD

**Issue by mikael1017** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#7]
**Describe the bug**
I can't create an account with some date of birth

**To Reproduce**
1. Go to main page
2. Click on Create Account
3. Select 18, 11, 1941 for DOB

**Expected behavior**

**Screenshots**
<img width="449" alt="Screen Shot 2022-07-07 at 6 39 23 PM" src="https://user-images.githubusercontent.com/59891471/177899492-ac3b777f-d38c-427c-99c2-8c5ddf7c2cbb.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook
 - OS: Mac OS Monterey
 - Browser: Chrome
 - Version 102.0.5005.115

**Additional context**

**Comment by george-q-liu** [comment]
fixed
