### ISSUE TITLE
Feature: Make recommended list of friends 

### ISSUE THREAD

**Issue by bonicim** [neu-seattle-cs5500-summer2022/project-SM22-h9shen1997-georgeliu614-zheli1001#9]
**Describe the bug**
As a new user, I don't know anyone. I would like the app to recommend friends to me. If I don't have friends in real life, I don't know who to search for. So it would be nice for the application to recommend me friends.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by george-q-liu** [comment]
We really tried this in multiple ways. however we realized that friend recommendation is actually super complex and it's kinda out of the scope of this project.
